In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [5]:
path_to_file = '/content/shakespeare.txt'

In [6]:
text = open(path_to_file, 'r').read()

In [7]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [8]:
vocab = sorted(set(text))

In [9]:
# Will be needed for the last dense layer

len(vocab)

84

In [10]:
# Step 2 of Text Processing 
# Vectorize the text and
# Create Encoding Dictionary

In [11]:
# We will assign integer value to each charecter
#for pair in enumerate(vocab):
 #   print(pair)

In [12]:
# now storing the integer charecter pair
char_to_ind = {u:i for i, u in enumerate(vocab)}

In [13]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [14]:
# Reverse list of char_to_integer
ind_to_char = np.array(vocab)

In [15]:
print(ind_to_char[33])
print(char_to_ind['H'])

H
33


In [16]:
# Now replace all charecters with the integer value
encoded_text = np.array([char_to_ind[c] for c in text])

In [17]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [18]:
text[:500]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [19]:
encoded_text.shape

(5445609,)

In [20]:
# Step 3 of Creating Batches 
# Understand text sequences
# Use Tf dataset to create batches
# Shuffle batches

In [21]:
# We are trying to find a pattern
# Printing out single line and three lines, we see that there is a pattern
# So we are going to measure charecter length of 3 lines and taking our sequence length
# Always try to analyze the data to find out the pattern

line = "From fairest creatures we desire increase"
print(len(line))

part_stanza = """From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,"""
print(len(part_stanza))

41
131


In [22]:
seq_len = 120

In [23]:
total_no_seq = int(len(text) / (seq_len+1))
total_no_seq

45005

In [24]:
# Create Training Sequences
# with special tensorflow dataset object
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)


In [25]:
type(char_dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [26]:
for i in char_dataset.take(500):
     print(i)
     print(i.numpy())

tf.Tensor(0, shape=(), dtype=int64)
0
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(12, shape=(), dtype=int64)
12
tf.Tensor(0, shape=(), dtype=int64)
0
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(

In [27]:
for i in char_dataset.take(500):
     print(ind_to_char[i.numpy()])



 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1


 
 
F
r
o
m
 
f
a
i
r
e
s
t
 
c
r
e
a
t
u
r
e
s
 
w
e
 
d
e
s
i
r
e
 
i
n
c
r
e
a
s
e
,


 
 
T
h
a
t
 
t
h
e
r
e
b
y
 
b
e
a
u
t
y
'
s
 
r
o
s
e
 
m
i
g
h
t
 
n
e
v
e
r
 
d
i
e
,


 
 
B
u
t
 
a
s
 
t
h
e
 
r
i
p
e
r
 
s
h
o
u
l
d
 
b
y
 
t
i
m
e
 
d
e
c
e
a
s
e
,


 
 
H
i
s
 
t
e
n
d
e
r
 
h
e
i
r
 
m
i
g
h
t
 
b
e
a
r
 
h
i
s
 
m
e
m
o
r
y
:


 
 
B
u
t
 
t
h
o
u
 
c
o
n
t
r
a
c
t
e
d
 
t
o
 
t
h
i
n
e
 
o
w
n
 
b
r
i
g
h
t
 
e
y
e
s
,


 
 
F
e
e
d
'
s
t
 
t
h
y
 
l
i
g
h
t
'
s
 
f
l
a
m
e
 
w
i
t
h
 
s
e
l
f
-
s
u
b
s
t
a
n
t
i
a
l
 
f
u
e
l
,


 
 
M
a
k
i
n
g
 
a
 
f
a
m
i
n
e
 
w
h
e
r
e
 
a
b
u
n
d
a
n
c
e
 
l
i
e
s
,


 
 
T
h
y
 
s
e
l
f
 
t
h
y
 
f
o
e
,
 
t
o
 
t
h
y
 
s
w
e
e
t
 
s
e
l
f
 
t
o
o
 
c
r
u
e
l
:


 
 
T
h
o
u
 
t
h
a
t
 
a
r
t
 
n
o
w
 
t
h
e
 
w
o
r
l
d
'
s
 
f
r
e
s
h
 
o
r
n
a
m
e
n
t
,


 
 
A
n
d
 
o
n
l
y
 
h
e
r
a
l
d
 
t
o
 
t
h
e
 
g
a
u
d
y
 
s
p
r
i
n
g
,


 
 
W
i
t
h
i
n
 
t
h
i
n
e
 
o
w
n
 
b
u


In [28]:
# We have sliced each charecter 
# Now will call batch method to create our batrches
# drop_remainder=True cause we don't have perfect number of sequence, we had some reminder

sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

In [29]:
# We will create our target sequences by three steps
# 1. Grab input text 2. Target Sequence = Input text but shifted one charecter 3. Make tuple of this two
# So create a method for this

def create_seq_targets(seq):
    input_txt = seq[:-1] # Hello my nam
    target_txt = seq[1:] # ello my name
    return input_txt, target_txt

In [30]:
dataset = sequences.map(create_seq_targets)

In [31]:
for input_txt, target_txt in  dataset.take(2):
    print('\n')
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    # There is an extra whitespace!
    print(''.join(ind_to_char[target_txt.numpy()]))



[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


[56 74  1 75 63 60  

In [32]:
# here we are shuffling charecters but sequence wise
# maybe
# otherwise there will be no meaningful sequences
# here batch size is 128. means we will feed 128 sequences at a time

In [33]:
# Batch size
batch_size = 128

# Buffer size to shuffle the dataset so it doesn't attempt to shuffle
# the entire sequence in memory. Instead, it maintains a buffer in which it shuffles elements
buffer_size = 10000

dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [34]:
dataset

<BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

In [35]:
# Creating Model
# 1. Create loss Function 2. Embedding - GRU - and lastly Dense Layer

In [36]:
vocab_size = len(vocab)
print(vocab_size)

84


In [37]:
# Embeded dimension more or less to vocab_size 
embed_dim =64 

In [38]:
# More neurons
rnn_neurons = 1026

In [39]:
# Creating Loss function
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [40]:
# We want from_logits=True which is false by default. Thats why creating custom function
# from_logits=True means the input to crossEntropy layer is normal tensor/logits,
# while if from_logits=False, means the input is a probability and usually you should have some softmax activation in your last layer.

def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [41]:
# Now we will create our model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU

In [42]:
#Embeddings are dense numerical representations of real-world objects and relationships,
#expressed as a vector. The vector space quantifies the semantic similarity between categories.
#Embedding vectors that are close to each other are considered similar.

In [43]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))
    model.compile(optimizer='adam', loss=sparse_cat_loss) 
    return model

In [44]:
model = create_model(
  vocab_size = vocab_size,
  embed_dim=embed_dim,
  rnn_neurons=rnn_neurons,
  batch_size=batch_size)

In [45]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (128, None, 64)           5376      
                                                                 
 gru (GRU)                   (128, None, 1026)         3361176   
                                                                 
 dense (Dense)               (128, None, 84)           86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [46]:
for input_example_batch, target_example_batch in dataset.take(1):

  # Predict off some random batch
  example_batch_predictions = model(input_example_batch)

In [47]:
example_batch_predictions.shape

TensorShape([128, 120, 84])

In [48]:
example_batch_predictions[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[-6.2840986e-03, -3.9266292e-03, -3.4835676e-04, ...,
        -2.1999478e-03,  1.6070357e-04,  3.0153508e-03],
       [-3.1294965e-03, -5.5738813e-03, -2.0252294e-03, ...,
         4.6860334e-03,  7.5447035e-04,  2.1636414e-03],
       [ 3.0643481e-03,  1.5279120e-04, -8.8883811e-05, ...,
        -3.2402219e-03,  3.6150396e-03, -8.7526524e-03],
       ...,
       [-1.0590103e-02,  4.0940140e-04, -3.7801266e-03, ...,
         2.1986982e-03, -2.9724438e-03, -1.5542648e-03],
       [-8.1364550e-03, -2.0657962e-03, -6.0883122e-03, ...,
        -3.9967606e-03, -3.6188655e-03, -4.9872338e-03],
       [-1.5562160e-03, -4.4250966e-04,  2.4519777e-03, ...,
        -3.9499938e-03,  1.2827308e-03, -1.1375470e-03]], dtype=float32)>

In [49]:
# here we are considering all values but drawing one single value with maximum value row wise

sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [50]:
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[37],
       [22],
       [35],
       [69],
       [81],
       [16],
       [24],
       [34],
       [27],
       [15],
       [62],
       [81],
       [69],
       [43],
       [17],
       [17],
       [21],
       [79],
       [ 7],
       [73],
       [11],
       [28],
       [30],
       [48],
       [19],
       [70],
       [81],
       [ 0],
       [69],
       [52],
       [19],
       [57],
       [53],
       [25],
       [81],
       [ 8],
       [64],
       [19],
       [19],
       [79],
       [65],
       [18],
       [ 2],
       [10],
       [71],
       [15],
       [54],
       [18],
       [52],
       [41],
       [72],
       [39],
       [ 7],
       [70],
       [69],
       [13],
       [66],
       [42],
       [ 6],
       [51],
       [80],
       [63],
       [46],
       [12],
       [12],
       [67],
       [75],
       [54],
       [68],
       [56],
       [75],
       [ 5],
       [72],
   

In [51]:
# Reformat to not be a lists of lists
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [52]:

sampled_indices 

array([37, 22, 35, 69, 81, 16, 24, 34, 27, 15, 62, 81, 69, 43, 17, 17, 21,
       79,  7, 73, 11, 28, 30, 48, 19, 70, 81,  0, 69, 52, 19, 57, 53, 25,
       81,  8, 64, 19, 19, 79, 65, 18,  2, 10, 71, 15, 54, 18, 52, 41, 72,
       39,  7, 70, 69, 13, 66, 42,  6, 51, 80, 63, 46, 12, 12, 67, 75, 54,
       68, 56, 75,  5, 72, 62, 58, 81, 55, 48,  8, 55, 77, 76, 51, 65, 66,
       15, 57,  7, 54, 51, 23,  2, 60, 52,  7, 28, 32, 72, 82, 30, 69, 33,
        1, 12, 10, 45, 64, 39, 27, 54, 32, 77, 56, 41, 33,  6, 55, 38, 20,
        3])

In [53]:
ind_to_char[sampled_indices]

array(['L', ';', 'J', 'n', 'z', '5', '>', 'I', 'B', '4', 'g', 'z', 'n',
       'R', '6', '6', ':', 'x', ')', 'r', '0', 'C', 'E', 'W', '8', 'o',
       'z', '\n', 'n', '[', '8', 'b', ']', '?', 'z', ',', 'i', '8', '8',
       'x', 'j', '7', '!', '.', 'p', '4', '_', '7', '[', 'P', 'q', 'N',
       ')', 'o', 'n', '2', 'k', 'Q', '(', 'Z', 'y', 'h', 'U', '1', '1',
       'l', 't', '_', 'm', 'a', 't', "'", 'q', 'g', 'c', 'z', '`', 'W',
       ',', '`', 'v', 'u', 'Z', 'j', 'k', '4', 'b', ')', '_', 'Z', '<',
       '!', 'e', '[', ')', 'C', 'G', 'q', '|', 'E', 'n', 'H', ' ', '1',
       '.', 'T', 'i', 'N', 'B', '_', 'G', 'v', 'a', 'P', 'H', '(', '`',
       'M', '9', '"'], dtype='<U1')

In [54]:
# Now training the model
#epochs = 30
#model.fit(dataset,epochs=epochs)

In [55]:
from tensorflow.keras.models import load_model

In [56]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

model.load_weights('/content/shakespeare_gen.h5')

model.build(tf.TensorShape([1, None]))

In [57]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (1, None, 64)             5376      
                                                                 
 gru_1 (GRU)                 (1, None, 1026)           3361176   
                                                                 
 dense_1 (Dense)             (1, None, 84)             86268     
                                                                 
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [79]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
  '''
  model: Trained Model to Generate Text
  start_seed: Intial Seed text in string form
  gen_size: Number of characters to generate

  Basic idea behind this function is to take in some seed text, format it so
  that it is in the correct shape for our network, then loop the sequence as
  we keep adding our own predicted characters. Similar to our work in the RNN
  time series problems.
  '''

  # Number of characters to generate
  num_generate = gen_size

  # Vecotrizing starting seed text
  input_eval = [char_to_ind[s] for s in start_seed]
# Expand to match batch format shape
  input_eval = tf.expand_dims(input_eval, 0)
  print("initial",input_eval)

  # Empty list to hold resulting generated text
  text_generated = []

  # Temperature effects randomness in our resulting text
  # The term is derived from entropy/thermodynamics.
  # The temperature is used to effect probability of next characters.
  # Higher probability == lesss surprising/ more expected
  # Lower temperature == more surprising / less expected
 
  temperature = temp

  # Here batch size == 1
  model.reset_states()

  for i in range(num_generate):

      # Generate Predictions
      predictions = model(input_eval)

      # Remove the batch shape dimension
      predictions = tf.squeeze(predictions, 0)

      # Use a cateogircal disitribution to select the next character
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # Pass the predicted charracter for the next input
      input_eval = tf.expand_dims([predicted_id], 0)
      print("loop",input_eval)
      # Transform back to character letter
      text_generated.append(ind_to_char[predicted_id])
      

  return (start_seed + ''.join(text_generated))

In [80]:
#print(generate_text(model,"flower",gen_size=1000))
generate_text(model,"flower",gen_size=1000)

initial tf.Tensor([[61 67 70 78 60 73]], shape=(1, 6), dtype=int32)
loop tf.Tensor([[5]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[74]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[1]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[74]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[70]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[69]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[1]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[70]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[61]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[1]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[63]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[60]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[56]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[77]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[60]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[69]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[8]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[0]], shape=(1, 1), dtype=int32)
loop tf.Tensor([[1]], shape=(1, 1), dt

"flower's son of heaven,\n    Looking to see wrath, and beseech your honour.\n    Ah, sirrah, prosper not secure; but I hase suspect my head is on the hands, drinks in the first corruprend habit, and hast thou mad-\n    Your high proclaim I shall lend the right.\n  PORTIA. If there be torse to transform me away,\n    And it not know her silken priest, and fore o' day was; for what importion a\n    legatening green wars, or the humour'd of his sleeve?\n  are these points\n    To his most mighty friends.- for a wife! What sayest thou!\n\n                     Enter DIOMEDESSE\n\n    And to your mother's court, by this my spirit,\n    Tell's Majeove your soften victory of our fire? Thou art not mad;\n    let me be a right. They should not speak our youth\n    on Gloucester, and told me: he 'tis time for my daughter, and\n    thou giv'st them gracious along.\n  LEONTES. We'll hear my honourable Rivall I'll help thee in place- I'll\n                            Exeunt\n\n\n\n\nACT III. SCENE 